### ISSUE TITLE
Regex is incorrect (does not accurately parse GitHub usernames)

### ISSUE THREAD

**Issue by niftylettuce** [remarkjs/remark-github#13]
I get the following error with the following `package.json` "repository" field:

```sh
CHANGELOG.md
  1:1  error  Error: Missing `repository` field in `options`
    at Function.github (/Users/user/Projects/color-convert/node_modules/remark-github/lib/index.js:76:11)
```

Repository  value: `https://github.com/Qix-/color-convert`

I believe the trailing `-` on the username is causing it to fail.

**Comment by wooorm** [comment]
Weird!

<img width="425" alt="screen shot 2018-06-20 at 19 44 57" src="https://user-images.githubusercontent.com/944406/41675248-761b49e0-74c2-11e8-98b4-bdb1bf4ef3f3.png">

I guess they changed that later? Do you know of any other guideline where GH themselves parse handles?

**Comment by niftylettuce** [comment]
No idea

**Comment by wooorm** [comment]
https://github.com/shinnn/github-username-regex/issues/1

Feel free to submit a PR
