### ISSUE TITLE
Support repositories including dots

### ISSUE THREAD

**Issue by yuku** [remarkjs/remark-github#14]
## What

It seems that remark-github ignores repositories including dots in their name such as wooorm/wooorm.github.io.

### Example

When input is (markdown):

```markdown
https://github.com/wooorm/wooorm.github.io/commit/c01f
```

expected output is (html):

```html
<a href="https://github.com/wooorm/wooorm.github.io/commit/c01f">
  wooorm/wooorm.github.io@<code>c01f</code>
</a>
```

but actual output is (html):

```html
<a href="https://github.com/wooorm/wooorm.github.io/commit/c01f">
  https://github.com/wooorm/wooorm.github.io/commit/c01f
</a>
```

## Why

Because GitHub do so: https://github.com/wooorm/wooorm.github.io/commit/c01f

**Comment by Murderlon** [comment]
Thanks for catching and reporting this. You're right, the expected behavior is how it should work.
