### ISSUE TITLE
remark-github treats '.YYYYMMDD' as a commit ID.

### ISSUE THREAD

**Issue by trustin** [remarkjs/remark-github#22]
### Subject of the issue

For example, `2.10.2.20200130` (a version number) is rendered as:

```markdown
2.10.2.[2020013](https://github.com/remarkjs/remark-github/commit/20200130)
```

when it's expected to be rendered in verbatim. Also, note the omission of the trailing `0`.

### Your environment

*   **OS**: Linux
*   **Packages**: `remark-github` 9.0.0 (via `gatsby-plugin-mdx`)
*   **Env**: node 12.16.2, yarn 1.22.4, gatsby 2.20.29, gatsby-plugin-mdx 1.1.10

### Steps to reproduce

Try to render `2.10.2.20200130` in an MDX file.

### Expected behaviour

- `2.10.2.20200130` should be rendered as it is.
- The digits without a leading whitespace should not be treated as a commit ID.

### Actual behaviour

`2.10.2.20200130` is rendered incorrectly:

```markdown
2.10.2.[2020013](https://github.com/remarkjs/remark-github/commit/20200130)
```

**Comment by trustin** [comment]
In case of Github:

- aba315b is treated as a commit ID.
- 2.10.2.aba315b is not treated as a commit ID.

**Comment by wooorm** [comment]
Hi there! 👋

484350121c131b1818df6fac8c7561aeb9947251 is valid sha here, starting with lots of non-hex-digits, and indeed, it doesn’t link:

2.10.2.48435012

GitHub performs a check whether a SHA exists, which we can’t do (it would be too expensive):
48435012
48435013

GitHub also doesn’t publish how this works exactly, so we’ll have to reverse engineer that.

Fix would be to tighten this regex:

https://github.com/remarkjs/remark-github/blob/168480ad9bc6bf88bbf2c86c00e4bd58b50193a8/lib/tokenizer/hash.js#L10

...not exactly sure how tight to do it though.

**Comment by trustin** [comment]
As you might noticed, even if 4843501 is a valid SHA, 2.10.2.4843501 is not treated as a SHA.

**Comment by wooorm** [comment]
Yeah I noticed that (“and indeed, it doesn’t link:”)

**Comment by wooorm** [comment]
Do you have any thoughts on how to tighten that regex?

**Comment by wooorm** [comment]
Fixed, released in 9.0.1!

**Comment by trustin** [comment]
Thank you so much, @wooorm! Sorry that I didn't have a chance to provide a meaningful feed back on your last question. 🙇

**Comment by wooorm** [comment]
Great, and no problem!
