### ISSUE TITLE
Add option to customize generated <a> tags

### ISSUE THREAD

**Issue by jamesdh** [remarkjs/remark-github#26]
### Subject of the feature

The ability to customize the generated <a> tags w/ options such as...

```javascript
{target: '_blank', ref: 'external'}
```

### Problem

The primary use case is to define `target="_blank"` to open links in a new tab. 

### Expected behavior

Whatever valid options are defined are added to the generated anchor tags.

### Alternatives

There is [remark-external-links](https://github.com/remarkjs/remark-external-links) but unfortunately that only gets applied against the source markdown. These links exist only in their generated html and so it cannot be applied to them.

**Comment by jamesdh** [comment]
I just realized [react-markdown](https://github.com/remarkjs/react-markdown) has a `linkTarget` prop which takes care of this for me!

**Comment by wooorm** [comment]
That's something for plugins. remark-external-links does this. Or in deed, react-markdown!
