### ISSUE TITLE
[Feature request] Allow transform links only

### ISSUE THREAD

**Issue by Airkro** [remarkjs/remark-github#36]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

We want to keep references as text and transform links only.

### Solution

When `options.repository` == false, disable references transform.

### Alternatives

No.

**Comment by Airkro** [comment]
Keep references as text, don't touch them:

```markdown
*   Commit: f8083175fe890cbf14f41d0a06e7aa35d4989587
*   Commit (fork): foo@f8083175fe890cbf14f41d0a06e7aa35d4989587
*   Commit (repo): remarkjs/remark@e1aa9f6c02de18b9459b7d269712bcb50183ce89
*   Issue or PR (`#`): #1
*   Issue or PR (`GH-`): GH-1
*   Issue or PR (fork): foo#1
*   Issue or PR (project): remarkjs/remark#1
*   Mention: @wooorm
```

And transform links:

```markdown
*   Commit: <https://github.com/remarkjs/remark/commit/e1aa9f6c02de18b9459b7d269712bcb50183ce89>
*   Commit comment: <https://github.com/remarkjs/remark/commit/ac63bc3abacf14cf08ca5e2d8f1f8e88a7b9015c#commitcomment-16372693>
*   Issue or PR: <https://github.com/remarkjs/remark/issues/182>
*   Issue or PR comment: <https://github.com/remarkjs/remark-github/issues/3#issue-151160339>
*   Mention: <https://github.com/ben-eb>
```

**Comment by wooorm** [comment]
- I’m not sure, this project tries to match how markdown is rendered in issues/PRs/comments on GitHub, that’s not what GitHub does
- “Link transforming” also uses `options.repository`, we can’t do it without

**Comment by Airkro** [comment]
Sound's reasonable but... I don't know what to say.

> I’m not sure, this project tries to match how markdown is rendered in issues/PRs/comments on GitHub, that’s not what GitHub does

A subset of "what GitHub does" is not that bad?

> “Link transforming” also uses `options.repository`, we can’t do it without

It does but it doesn't have to...

**Comment by Airkro** [comment]
I will make a folk version.
Before that, I always talk to maintainers to find out they want it or not (and what I miss).
Now I know the answer is no. I make a `remark-github-links` someday.

**Comment by wooorm** [comment]
Yeah, that’s good!

Though, I haven’t decided yet. I can’t decide yet. Because what you’re asking doesn’t work (`repository: false` will break linking, which needs a repository) and I don’t understand how you want it to work.

**Comment by Airkro** [comment]
We know what Github URL like:

```markdown
<https://github.com/remarkjs/remark/issues/182>
↓
[remarkjs/remark#182](https://github.com/remarkjs/remark/issues/182)
```

I think `options.repository` is not needed. 

In many cases, we don't need to compare `options.repository` with repository info in the link in the same repo or not.

**Comment by wooorm** [comment]
As I understand it, you want behavior that GitHub does not provide.
Instead of handling these links, as GH does in relation to a certain repo, you want links to be handled regardless of repo.
So the behavior you’re looking for is not just a part of this plugin, but a new part to this this plugin.
I can understand such additions for many plugins, but the goal of this plugin is **to match GitHub**. So I think it’s best to put the behavior you want in a separate plugin.

Good luck!
