### ISSUE TITLE
Missing or invalid `repository` field in `options`

### ISSUE THREAD

**Issue by sw-yx** [remarkjs/remark-github#42]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

latest

### Link to runnable example

https://codesandbox.io/s/cool-swirles-vbp4nr?file=/src/index.js

### Steps to reproduce

as above in codesandbox

### Expected behavior

either the `repository` field is optional, in which case it should not error, or the docs and code samples should show that it is required

### Actual behavior

![image](https://user-images.githubusercontent.com/6764957/183315836-232151b0-bf32-4dba-a927-d882471aa4a9.png)

**Comment by KimPinot** [comment]
It seems you waited this repository expression for example `#2`
Did you add options like this?
```
.use(remarkGithub, [
  {
    repository: "your-id/your-repo",
  }
])
```

**Comment by wooorm** [comment]
> either the repository field is optional, in which case it should not error, or the docs and code samples should show that it is required

It is optional in some environments (Node.js). (In the future Deno or whatever else has alternatives to `node:fs`). It can’t be optional in browsers.

I’m not sure how to handle this other than: type-wise and in the typical-case it is optional. In some cases that doesn‘t work and you get a runtime error ASAP when that’s the case.

What do you suggest to these docs? https://github.com/remarkjs/remark-github#optionsrepository

**Comment by wooorm** [comment]
Closing as `options.repository` is in several cases optional. Open to hearing on what language you think would make it more clear in which cases it isn’t
