### ISSUE TITLE
[Feature Request] Support repo url.

### ISSUE THREAD

**Issue by JiangWeixian** [remarkjs/remark-github#43]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

In README, plugin currently only support issues, commits, comments, users...

It looks like `https://github.com/remarkjs/remark-github` will not render to [remarkjs/remark-github](https://github.com/remarkjs/remark-github). Would like support it in the future? thx

### Solution

`https://github.com/remarkjs/remark-github` -> [remarkjs/remark-github](https://github.com/remarkjs/remark-github)

### Alternatives

Write a custom remark plugin

**Comment by wooorm** [comment]
GitHub does not do that:

```
alpha https://github.com/remarkjs/remark-github bravo
```

alpha https://github.com/remarkjs/remark-github bravo

…so I don’t think it makes sense in this project. You can write an external plugin.

**Comment by wooorm** [comment]
Note: Refined GitHub *does* do this: https://github.com/refined-github/refined-github.
That’s not a core part of GitHub though.

**Comment by JiangWeixian** [comment]
A quick implement: https://github.com/JiangWeixian/remark-plugin-refined-github

Happy coding
