### ISSUE TITLE
Prevent autolinking for specific text?

### ISSUE THREAD

**Issue by slavafomin** [remarkjs/remark-github#44]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

Hello!

Is there a way to prevent autolinking for specific text, e.g. `@name`?

### Solution

Pending.

### Alternatives

Pending.

**Comment by wooorm** [comment]
`BuildUrl` can return `false` to not generate a link: https://github.com/remarkjs/remark-github#optionsbuildurl. It’s given an object, and also a `defaultBuildUrl`.
Here’s an example: https://github.com/remarkjs/remark-github#example-buildurl.
